/**
 * Anasayfa haritası — örnek referans kayıtları.
 * Tüm projeler, aynı ilde birden fazla kayıt (sevkiyat / farklı camiler) desteklenir.
 * Güncel liste ve görselleri CMS veya bu dosyadan yönetebilirsiniz.
 */

export type ReferenceCategory = 'kubbe' | 'nakkas' | 'oluk' | 'diger';

export type TurkeyReferenceProject = {
  id: string;
  /** "01" … "81" */
  plaka: string;
  mosqueName: string;
  cityLabel: string;
  category: ReferenceCategory;
  /** Örn. "2019" veya "2018 — restorasyon" */
  period?: string;
  /** Kart önizlemesi — public yolu */
  imageSrc?: string;
};

export const REFERENCE_KICKER = 'Türkiye genelinde referans';
export const REFERENCE_TITLE_REST = 'bizden izler';

/** Örnek veri — gerçek kayıtlarla değiştirin / genişletin */
export const TURKEY_REFERENCE_PROJECTS: readonly TurkeyReferenceProject[] = [
  {
    id: 'ank-1',
    plaka: '06',
    mosqueName: 'Hacı Bayram-ı Veli Camii',
    cityLabel: 'Ankara',
    category: 'kubbe',
    period: '2018',
  },
  {
    id: 'ank-2',
    plaka: '06',
    mosqueName: 'Kocatepe Camii',
    cityLabel: 'Ankara',
    category: 'nakkas',
    period: '2021',
    imageSrc: '/hizmetler/camii-nakkas-susleme.webp',
  },
  {
    id: 'ank-3',
    plaka: '06',
    mosqueName: 'Cami kubbe sevkiyatı',
    cityLabel: 'Ankara',
    category: 'kubbe',
    period: '2023',
  },
  {
    id: 'ist-1',
    plaka: '34',
    mosqueName: 'Fatih Camii çevresi işleri',
    cityLabel: 'İstanbul',
    category: 'oluk',
    period: '2020',
  },
  {
    id: 'ist-2',
    plaka: '34',
    mosqueName: 'Kubbe kaplama — Anadolu yakası',
    cityLabel: 'İstanbul',
    category: 'kubbe',
    period: '2022',
    imageSrc: '/hizmetler/camii-kubbe-kaplama.webp',
  },
  {
    id: 'ist-3',
    plaka: '34',
    mosqueName: 'Alemi tedarik',
    cityLabel: 'İstanbul',
    category: 'diger',
    period: '2024',
    imageSrc: '/hizmetler/camii-alemleri.webp',
  },
  {
    id: 'kon-1',
    plaka: '42',
    mosqueName: 'Merkez cami kubbesi',
    cityLabel: 'Konya',
    category: 'kubbe',
    period: '2017',
    imageSrc: '/hizmetler/aluminyum-kubbe-kaplama.webp',
  },
  {
    id: 'kon-2',
    plaka: '42',
    mosqueName: 'Oluk montajı',
    cityLabel: 'Konya',
    category: 'oluk',
    period: '2023',
    imageSrc: '/hizmetler/oluk-satis-montaj.webp',
  },
  {
    id: 'izm-1',
    plaka: '35',
    mosqueName: 'Kubbe bakır işçiliği',
    cityLabel: 'İzmir',
    category: 'kubbe',
    period: '2019',
    imageSrc: '/hizmetler/bakir-kubbe-kaplama.webp',
  },
  {
    id: 'izm-2',
    plaka: '35',
    mosqueName: 'Alüminyum levha sevkiyatı',
    cityLabel: 'İzmir',
    category: 'diger',
    period: '2022',
    imageSrc: '/hizmetler/aluminyum-satis.webp',
  },
  {
    id: 'bur-1',
    plaka: '16',
    mosqueName: 'Ulu Camii çevresi',
    cityLabel: 'Bursa',
    category: 'kubbe',
    period: '2016',
  },
  {
    id: 'ant-1',
    plaka: '07',
    mosqueName: 'Sahil camii kubbesi',
    cityLabel: 'Antalya',
    category: 'kubbe',
    period: '2021',
  },
  {
    id: 'ant-2',
    plaka: '07',
    mosqueName: 'Nakkaş süsleme',
    cityLabel: 'Antalya',
    category: 'nakkas',
    period: '2024',
  },
  {
    id: 'mer-1',
    plaka: '33',
    mosqueName: 'Kubbe kaplama',
    cityLabel: 'Mersin',
    category: 'kubbe',
    period: '2020',
  },
  {
    id: 'gaz-1',
    plaka: '27',
    mosqueName: 'Cami alemi',
    cityLabel: 'Gaziantep',
    category: 'diger',
    period: '2022',
    imageSrc: '/hizmetler/camii-alemleri.webp',
  },
  {
    id: 'tra-1',
    plaka: '61',
    mosqueName: 'Kubbe yenileme',
    cityLabel: 'Trabzon',
    category: 'kubbe',
    period: '2019',
  },
  {
    id: 'sam-1',
    plaka: '55',
    mosqueName: 'Oluk sistemi',
    cityLabel: 'Samsun',
    category: 'oluk',
    period: '2023',
  },
  {
    id: 'erz-1',
    plaka: '25',
    mosqueName: 'Kurşun örtü',
    cityLabel: 'Erzurum',
    category: 'diger',
    period: '2018',
    imageSrc: '/hizmetler/kursun-levha-satis.webp',
  },
  {
    id: 'van-1',
    plaka: '65',
    mosqueName: 'Kubbe uygulaması',
    cityLabel: 'Van',
    category: 'kubbe',
    period: '2020',
  },
  {
    id: 'diy-1',
    plaka: '21',
    mosqueName: 'Sevkiyat + montaj',
    cityLabel: 'Diyarbakır',
    category: 'kubbe',
    period: '2021',
  },
  {
    id: 'urf-1',
    plaka: '63',
    mosqueName: 'Kubbe kaplama',
    cityLabel: 'Şanlıurfa',
    category: 'kubbe',
    period: '2022',
  },
  {
    id: 'kay-1',
    plaka: '38',
    mosqueName: 'Nakkaş restorasyonu',
    cityLabel: 'Kayseri',
    category: 'nakkas',
    period: '2023',
  },
  {
    id: 'nev-1',
    plaka: '50',
    mosqueName: 'Peribacaları bölgesi camii',
    cityLabel: 'Nevşehir',
    category: 'kubbe',
    period: '2019',
  },
  {
    id: 'den-1',
    plaka: '20',
    mosqueName: 'Alüminyum kubbe',
    cityLabel: 'Denizli',
    category: 'kubbe',
    period: '2024',
    imageSrc: '/hizmetler/aluminyum-kubbe-kaplama.webp',
  },
  {
    id: 'esk-1',
    plaka: '26',
    mosqueName: 'Metal işleri',
    cityLabel: 'Eskişehir',
    category: 'diger',
    period: '2020',
  },
  {
    id: 'adn-1',
    plaka: '01',
    mosqueName: 'Merkez camii',
    cityLabel: 'Adana',
    category: 'kubbe',
    period: '2022',
  },
  {
    id: 'hat-1',
    plaka: '31',
    mosqueName: 'Sınır bölgesi proje',
    cityLabel: 'Hatay',
    category: 'oluk',
    period: '2023',
  },
  {
    id: 'bolu-beyaz-2015',
    plaka: '14',
    mosqueName: 'Bolu Beyaz Alüminyum',
    cityLabel: 'Bolu',
    category: 'kubbe',
    period: '9 Ocak 2015',
    imageSrc: '/hizmetler/bolu-beyaz-aluminyum.webp',
  },
  {
    id: 'yalova-bahcelievler-2015',
    plaka: '77',
    mosqueName: 'Yalova Bahçelievler — Siyah Alüminyum Kaplama',
    cityLabel: 'Yalova',
    category: 'kubbe',
    period: '22 Ocak 2015',
    imageSrc: '/hizmetler/yalova-bahcelievler-siyah-aluminyum.webp',
  },
  {
    id: 'inegol-kuba-2015',
    plaka: '16',
    mosqueName: 'İnegöl Küba Camii — Beyaz Alüminyum Kaplama',
    cityLabel: 'İnegöl (Bursa)',
    category: 'kubbe',
    period: '28 Ocak 2015',
    imageSrc: '/hizmetler/inegol-kuba-camii-beyaz-aluminyum.webp',
  },
  {
    id: 'istanbul-yesil-aluminyum-2015',
    plaka: '34',
    mosqueName: 'İstanbul — Yeşil Alüminyum satışımız',
    cityLabel: 'İstanbul',
    category: 'diger',
    period: '9 Ocak 2015',
    imageSrc: '/hizmetler/istanbul-yesil-aluminyum-satis.webp',
  },
  {
    id: 'midyat-muhammed-emin-2015',
    plaka: '47',
    mosqueName: 'Midyat Muhammed Emin Camii — Beyaz Alüminyum Kaplama',
    cityLabel: 'Midyat (Mardin)',
    category: 'kubbe',
    period: '2 Şubat 2015',
    imageSrc: '/hizmetler/midyat-muhammed-emin-beyaz-aluminyum.webp',
  },
  {
    id: 'didim-akbuk-yavuz-selim-2015',
    plaka: '09',
    mosqueName: 'Didim Akbük Yavuz Sultan Selim Camii — Siyah Alüminyum Kaplama',
    cityLabel: 'Akbük, Didim (Aydın)',
    category: 'kubbe',
    period: '8 Şubat 2015',
    imageSrc: '/hizmetler/didim-akbuk-yavuz-sultan-selim-camii.webp',
  },
  {
    id: 'ceyhan-tas-restorasyon-2015',
    plaka: '01',
    mosqueName: 'Ceyhan — Taş restorasyon',
    cityLabel: 'Ceyhan (Adana)',
    category: 'diger',
    period: '25 Haziran 2015',
    imageSrc: '/hizmetler/ceyhan-tas-restorasyon.webp',
  },
  {
    id: 'samsun-malkara-ahi-evran-2015',
    plaka: '55',
    mosqueName: 'Malkara Ahi Evran Köyü — Beyaz Alüminyum Kaplama',
    cityLabel: 'Ahi Evran Köyü (Samsun)',
    category: 'kubbe',
    period: '26 Haziran 2015',
    imageSrc: '/hizmetler/malkara-ahi-evran-samsun-beyaz-aluminyum.webp',
  },
  {
    id: 'ankara-demetevler-ertugrulgazi-2015',
    plaka: '06',
    mosqueName: 'Demetevler Ertuğrulgazi Camii',
    cityLabel: 'Ankara (Demetevler)',
    category: 'kubbe',
    period: '26 Haziran 2015',
    imageSrc: '/hizmetler/ankara-demetevler-ertugrulgazi-camii.webp',
  },
  {
    id: 'yozgat-cekerek-beyaz-aluminyum-2015',
    plaka: '66',
    mosqueName: 'Çekerek — Beyaz Alüminyum Kubbe Kaplama',
    cityLabel: 'Çekerek (Yozgat)',
    category: 'kubbe',
    period: '6 Eylül 2015',
    imageSrc: '/hizmetler/yozgat-cekerek-beyaz-aluminyum.webp',
  },
  {
    id: 'amasya-yildirim-beyazit-camii-2015',
    plaka: '05',
    mosqueName: 'Yıldırım Beyazıt Camii',
    cityLabel: 'Amasya',
    category: 'kubbe',
    period: '26 Ekim 2015',
    imageSrc: '/hizmetler/amasya-yildirim-beyazit-camii.webp',
  },
  {
    id: 'amasya-hz-omer-camii-2015',
    plaka: '05',
    mosqueName: 'Hz Ömer Camii',
    cityLabel: 'Amasya',
    category: 'kubbe',
    period: '12 Kasım 2015',
    imageSrc: '/hizmetler/amasya-hz-omer-camii.webp',
  },
  {
    id: 'osmaniye-asim-kocabiyik-camii-2016',
    plaka: '80',
    mosqueName: 'Asım Kocabıyık Camii',
    cityLabel: 'Osmaniye',
    category: 'kubbe',
    period: '17 Ocak 2016',
    imageSrc: '/hizmetler/osmaniye-asim-kocabiyik-camii.webp',
  },
  {
    id: 'kahramanmaras-afsin-karsiyaka-camii-2016',
    plaka: '46',
    mosqueName: 'Afşin Karşıyaka Camii',
    cityLabel: 'Afşin (Kahramanmaraş)',
    category: 'kubbe',
    period: '22 Ocak 2016',
    imageSrc: '/hizmetler/kahramanmaras-afsin-karsiyaka-camii.webp',
  },
  {
    id: 'didim-yavuz-selim-camii-2016',
    plaka: '09',
    mosqueName: 'Yavuz Selim Camii',
    cityLabel: 'Didim (Aydın)',
    category: 'kubbe',
    period: '28 Ocak 2016',
    imageSrc: '/hizmetler/didim-yavuz-selim-camii.webp',
  },
  {
    id: 'adana-imamoglu-adalet-camii-2016',
    plaka: '01',
    mosqueName: 'İmamoğlu Adalet Camii',
    cityLabel: 'İmamoğlu (Adana)',
    category: 'kubbe',
    period: '14 Mart 2016',
    imageSrc: '/hizmetler/adana-imamoglu-adalet-camii.webp',
  },
  {
    id: 'istanbul-arnavutkoy-bogazkoy-merkez-camii-2016',
    plaka: '34',
    mosqueName: 'Boğazköy Merkez Camii',
    cityLabel: 'Boğazköy, Arnavutköy (İstanbul)',
    category: 'kubbe',
    period: '16 Mart 2016',
    imageSrc: '/hizmetler/istanbul-arnavutkoy-bogazkoy-merkez-camii.webp',
  },
  {
    id: 'adana-pozanti-kirinti-camii-2016',
    plaka: '01',
    mosqueName: 'Kırıntı Camii',
    cityLabel: 'Pozantı (Adana)',
    category: 'kubbe',
    period: '7 Mayıs 2016',
    imageSrc: '/hizmetler/adana-pozanti-kirinti-camii.webp',
  },
  {
    id: 'balikesir-susurluk-camii-2016',
    plaka: '10',
    mosqueName: 'Susurluk Camii',
    cityLabel: 'Susurluk (Balıkesir)',
    category: 'kubbe',
    period: '11 Mayıs 2016',
    imageSrc: '/hizmetler/balikesir-susurluk-camii.webp',
  },
  {
    id: 'amasya-merkez-elif-camii-2016',
    plaka: '05',
    mosqueName: 'Merkez Elif Camii',
    cityLabel: 'Merkez (Amasya)',
    category: 'kubbe',
    period: '11 Mayıs 2016',
    imageSrc: '/hizmetler/amasya-merkez-elif-camii.webp',
  },
  {
    id: 'sanliurfa-imam-hatip-lisesi-2016',
    plaka: '63',
    mosqueName: 'İmam Hatip Lisesi — Bakır kubbe',
    cityLabel: 'Şanlıurfa',
    category: 'kubbe',
    period: '28 Mayıs 2016',
    imageSrc: '/hizmetler/sanliurfa-imam-hatip-lisesi.webp',
  },
  {
    id: 'edirne-uzunkopru-merkez-camii-2016',
    plaka: '22',
    mosqueName: 'Merkez Camii',
    cityLabel: 'Uzunköprü (Edirne)',
    category: 'kubbe',
    period: '29 Haziran 2016',
    imageSrc: '/hizmetler/edirne-uzunkopru-merkez-camii.webp',
  },
  {
    id: 'istanbul-gurpinar-hz-hamza-camii-2016',
    plaka: '34',
    mosqueName: 'Hz. Hamza Camii',
    cityLabel: 'Gürpınar, Beylikdüzü (İstanbul)',
    category: 'kubbe',
    period: '1 Ağustos 2016',
    imageSrc: '/hizmetler/istanbul-gurpinar-hz-hamza-camii.webp',
  },
  {
    id: 'bursa-gemlik-selime-mahalle-camii-2016',
    plaka: '16',
    mosqueName: 'Selime Mahalle Camii',
    cityLabel: 'Gemlik (Bursa)',
    category: 'kubbe',
    period: '8 Ağustos 2016',
    imageSrc: '/hizmetler/bursa-gemlik-selime-mahalle-camii.webp',
  },
  {
    id: 'bursa-merkez-yunus-emre-camii-2016',
    plaka: '16',
    mosqueName: 'Yunus Emre Camii',
    cityLabel: 'Merkez (Bursa)',
    category: 'kubbe',
    period: '22 Ağustos 2016',
    imageSrc: '/hizmetler/bursa-merkez-yunus-emre-camii.webp',
  },
  {
    id: 'eskisehir-sanayi-camii-2016',
    plaka: '26',
    mosqueName: 'Sanayi Camii',
    cityLabel: 'Eskişehir',
    category: 'kubbe',
    period: '13 Ağustos 2016',
    imageSrc: '/hizmetler/eskisehir-sanayi-camii.webp',
  },
  {
    id: 'adana-soysalli-mahalle-camii-2016',
    plaka: '01',
    mosqueName: 'Soysallı Mahallesi Camii',
    cityLabel: 'Soysallı (Adana)',
    category: 'kubbe',
    period: '23 Ekim 2016',
    imageSrc: '/hizmetler/adana-soysalli-mahalle-camii.webp',
  },
  {
    id: 'istanbul-idris-nebi-vakfi-camii-2016',
    plaka: '34',
    mosqueName: 'İdris Nebi Vakfı Camii',
    cityLabel: 'İstanbul',
    category: 'kubbe',
    period: '24 Kasım 2016',
    imageSrc: '/hizmetler/istanbul-idris-nebi-vakfi-camii.webp',
  },
  {
    id: 'giresun-gorele-yesiltepe-camii-2017',
    plaka: '28',
    mosqueName: 'Yeşiltepe Camii',
    cityLabel: 'Görele (Giresun)',
    category: 'kubbe',
    period: '16 Şubat 2017',
    imageSrc: '/hizmetler/giresun-gorele-yesiltepe-camii.webp',
  },
  {
    id: 'adana-ceyhan-botas-tesisleri-camii-2017',
    plaka: '01',
    mosqueName: 'Botaş Tesisleri Camii — şadırvan',
    cityLabel: 'Ceyhan (Adana)',
    category: 'kubbe',
    period: '7 Nisan 2017',
    imageSrc: '/hizmetler/adana-ceyhan-botas-tesisleri-camii.webp',
  },
  {
    id: 'istanbul-gaziosmanpasa-cilekli-camii-2017',
    plaka: '34',
    mosqueName: 'Çilekli Camii',
    cityLabel: 'Gaziosmanpaşa (İstanbul)',
    category: 'kubbe',
    period: '14 Nisan 2017',
    imageSrc: '/hizmetler/istanbul-gaziosmanpasa-cilekli-camii.webp',
  },
  {
    id: 'ankara-hurdacilar-sitesi-camii-2017',
    plaka: '06',
    mosqueName: 'Hurdacılar Sitesi Camii',
    cityLabel: 'Hurdacılar Sitesi (Ankara)',
    category: 'kubbe',
    period: '17 Nisan 2017',
    imageSrc: '/hizmetler/ankara-hurdacilar-sitesi-camii.webp',
  },
  {
    id: 'mugla-fethiye-dodurga-koyu-camii-2017',
    plaka: '48',
    mosqueName: 'Dodurga Köyü Camii',
    cityLabel: 'Dodurga Köyü, Fethiye (Muğla)',
    category: 'kubbe',
    period: '25 Nisan 2017',
    imageSrc: '/hizmetler/mugla-fethiye-dodurga-koyu-camii.webp',
  },
  {
    id: 'kahramanmaras-onikisubat-muzdelife-camii-2017',
    plaka: '46',
    mosqueName: 'Müzdelife Camii',
    cityLabel: 'Onikişubat (Kahramanmaraş)',
    category: 'kubbe',
    period: '20 Nisan 2017',
    imageSrc: '/hizmetler/kahramanmaras-onikisubat-muzdelife-camii.webp',
  },
  {
    id: 'edirne-aluminyum-sevkiyati-2017',
    plaka: '22',
    mosqueName: 'Alüminyum sevkiyatı',
    cityLabel: 'Edirne',
    category: 'diger',
    period: '22 Nisan 2017',
    imageSrc: '/hizmetler/edirne-aluminyum-sevkiyati-2017.webp',
  },
  {
    id: 'kahramanmaras-onikisubat-hz-omer-camii-2017',
    plaka: '46',
    mosqueName: 'Hz. Ömer Camii',
    cityLabel: 'Onikişubat (Kahramanmaraş)',
    category: 'kubbe',
    period: '28 Nisan 2017',
    imageSrc: '/hizmetler/kahramanmaras-onikisubat-hz-omer-camii.webp',
  },
  {
    id: 'yozgat-sorgun-karakiz-koyu-camii-2017',
    plaka: '66',
    mosqueName: 'Karakız Köyü Camii',
    cityLabel: 'Karakız Köyü, Sorgun (Yozgat)',
    category: 'kubbe',
    period: '18 Mayıs 2017',
    imageSrc: '/hizmetler/yozgat-sorgun-karakiz-koyu-camii.webp',
  },
  {
    id: 'izmir-buca-bilal-i-habesi-camii-2017',
    plaka: '35',
    mosqueName: 'Bilal-i Habeşi Camii',
    cityLabel: 'Buca (İzmir)',
    category: 'kubbe',
    period: '26 Mayıs 2017',
    imageSrc: '/hizmetler/izmir-buca-bilal-i-habesi-camii.webp',
  },
  {
    id: 'eskisehir-odun-pazari-terzievler-camii-2017',
    plaka: '26',
    mosqueName: 'Terzievler Camii',
    cityLabel: 'Odun Pazarı (Eskişehir)',
    category: 'kubbe',
    period: '6 Haziran 2017',
    imageSrc: '/hizmetler/eskisehir-odun-pazari-terzievler-camii.webp',
  },
  {
    id: 'siirt-eruh-merkez-camii-2017',
    plaka: '56',
    mosqueName: 'Merkez Camii',
    cityLabel: 'Eruh (Siirt)',
    category: 'kubbe',
    period: '14 Haziran 2017',
    imageSrc: '/hizmetler/siirt-eruh-merkez-camii.webp',
  },
  {
    id: 'bursa-inegol-mesudiye-camii-2017',
    plaka: '16',
    mosqueName: 'Mesudiye Camii',
    cityLabel: 'İnegöl (Bursa)',
    category: 'kubbe',
    period: '19 Haziran 2017',
    imageSrc: '/hizmetler/bursa-inegol-mesudiye-camii.webp',
  },
  {
    id: 'antalya-aluminyum-sevkiyati-2017',
    plaka: '07',
    mosqueName: 'Alüminyum sevkiyatı',
    cityLabel: 'Antalya',
    category: 'diger',
    period: '19 Temmuz 2017',
    imageSrc: '/hizmetler/antalya-aluminyum-sevkiyati-2017.webp',
  },
  {
    id: 'hatay-altinozu-kamberli-koyu-camii-2017',
    plaka: '31',
    mosqueName: 'Kamberli Köyü Camii',
    cityLabel: 'Kamberli Köyü, Altınözü (Hatay)',
    category: 'kubbe',
    period: '7 Ağustos 2017',
    imageSrc: '/hizmetler/hatay-altinozu-kamberli-koyu-camii.webp',
  },
  {
    id: 'van-ipekyolu-molla-huseyn-i-bate-i-camii-2017',
    plaka: '65',
    mosqueName: 'Molla Hüseyn-i Bate-i Camii',
    cityLabel: 'İpekyolu (Van)',
    category: 'kubbe',
    period: '18 Ağustos 2017',
    imageSrc: '/hizmetler/van-ipekyolu-molla-huseyn-i-bate-i-camii.webp',
  },
  {
    id: 'giresun-sebin-karahisar-yavuz-selim-camii-2017',
    plaka: '28',
    mosqueName: 'Yavuz Selim Camii',
    cityLabel: 'Şebin Karahisar (Giresun)',
    category: 'kubbe',
    period: '28 Ağustos 2017',
    imageSrc: '/hizmetler/giresun-sebin-karahisar-yavuz-selim-camii.webp',
  },
  {
    id: 'izmir-aluminyum-sevkiyati-2017',
    plaka: '35',
    mosqueName: 'Alüminyum sevkiyatı',
    cityLabel: 'İzmir',
    category: 'diger',
    period: '29 Ağustos 2017',
    imageSrc: '/hizmetler/izmir-aluminyum-sevkiyati-2017.webp',
  },
  {
    id: 'duzce-merkez-konakli-koyu-camii-2017',
    plaka: '81',
    mosqueName: 'Konaklı Köyü Camii',
    cityLabel: 'Konaklı Köyü, Merkez (Düzce)',
    category: 'kubbe',
    period: '5 Eylül 2017',
    imageSrc: '/hizmetler/duzce-merkez-konakli-koyu-camii.webp',
  },
  {
    id: 'amasya-merkez-camii-2017',
    plaka: '05',
    mosqueName: 'Merkez Camii',
    cityLabel: 'Merkez (Amasya)',
    category: 'kubbe',
    period: '14 Eylül 2017',
    imageSrc: '/hizmetler/amasya-merkez-camii-2017.webp',
  },
  {
    id: 'hatay-altinozu-kamberli-koyu-camii-2017-eylul',
    plaka: '31',
    mosqueName: 'Kamberli Köyü Camii',
    cityLabel: 'Kamberli Köyü, Altınözü (Hatay)',
    category: 'kubbe',
    period: '19 Eylül 2017',
    imageSrc: '/hizmetler/hatay-altinozu-kamberli-koyu-2017-eylul.webp',
  },
  {
    id: 'hatay-payas-sehitlik-selcuklu-kubbe-sadirvan-2017',
    plaka: '31',
    mosqueName: 'Şehitlik — Selçuklu mimari kubbe şadırvan',
    cityLabel: 'Şehitlik, Payas (Hatay)',
    category: 'kubbe',
    period: '22 Eylül 2017',
    imageSrc: '/hizmetler/hatay-payas-sehitlik-selcuklu-kubbe-sadirvan.webp',
  },
  {
    id: 'aksaray-merkez-muhsin-yazicioglu-camii-2017',
    plaka: '68',
    mosqueName: 'Muhsin Yazıcıoğlu Camii',
    cityLabel: 'Merkez (Aksaray)',
    category: 'kubbe',
    period: '15 Ekim 2017',
    imageSrc: '/hizmetler/aksaray-merkez-muhsin-yazicioglu-camii.webp',
  },
  {
    id: 'adana-merkez-camii-2018',
    plaka: '01',
    mosqueName: 'Merkez Camii',
    cityLabel: 'Merkez (Adana)',
    category: 'kubbe',
    period: '13 Şubat 2018',
    imageSrc: '/hizmetler/adana-merkez-camii-2018.webp',
  },
  {
    id: 'erzincan-aluminyum-teslimati-2018',
    plaka: '24',
    mosqueName: 'Alüminyum teslimatı',
    cityLabel: 'Erzincan',
    category: 'diger',
    period: '16 Mart 2018',
    imageSrc: '/hizmetler/erzincan-aluminyum-teslimati-2018.webp',
  },
  {
    id: 'tekirdag-hayrabolu-camii-2018',
    plaka: '59',
    mosqueName: 'Hayrabolu Camii',
    cityLabel: 'Hayrabolu (Tekirdağ)',
    category: 'kubbe',
    period: '20 Nisan 2018',
    imageSrc: '/hizmetler/tekirdag-hayrabolu-camii-2018.webp',
  },
  {
    id: 'bursa-gazi-orhan-bey-camii-2018',
    plaka: '16',
    mosqueName: 'Gazi Orhan Bey Camii',
    cityLabel: 'Osmangazi (Bursa)',
    category: 'kubbe',
    period: '16 Mayıs 2018',
    imageSrc: '/hizmetler/bursa-gazi-orhan-bey-camii-2018.webp',
  },
  {
    id: 'denizli-merkez-akpinar-camii-2018',
    plaka: '20',
    mosqueName: 'Akpınar Camii',
    cityLabel: 'Akpınar, Merkez (Denizli)',
    category: 'kubbe',
    period: '8 Haziran 2018',
    imageSrc: '/hizmetler/denizli-merkez-akpinar-camii-2018.webp',
  },
  {
    id: 'istanbul-bakir-levha-sevkiyati-2018',
    plaka: '34',
    mosqueName: 'Bakır levha sevkiyatı',
    cityLabel: 'İstanbul',
    category: 'diger',
    period: '9 Haziran 2018',
    imageSrc: '/hizmetler/istanbul-bakir-levha-sevkiyati-2018.webp',
  },
  {
    id: 'bursa-inegol-turgut-alp-camii-2018',
    plaka: '16',
    mosqueName: 'Turgut Alp Camii',
    cityLabel: 'İnegöl (Bursa)',
    category: 'kubbe',
    period: '4 Temmuz 2018',
    imageSrc: '/hizmetler/bursa-inegol-turgut-alp-camii-2018.webp',
  },
  {
    id: 'cankiri-akcavakif-koyu-camii-2018',
    plaka: '18',
    mosqueName: 'Akçavakıf Köyü Camii',
    cityLabel: 'Akçavakıf Köyü (Çankırı)',
    category: 'kubbe',
    period: '26 Eylül 2018',
    imageSrc: '/hizmetler/cankiri-akcavakif-koyu-camii-2018.webp',
  },
  {
    id: 'osmaniye-duzici-akkoyunlu-camii',
    plaka: '80',
    mosqueName: 'Akkoyunlu Camii',
    cityLabel: 'Düziçi (Osmaniye)',
    category: 'kubbe',
    imageSrc: '/hizmetler/osmaniye-duzici-akkoyunlu-camii.webp',
  },
  {
    id: 'ankara-hacettepe-tarihi-eser-restorasyon-2018',
    plaka: '06',
    mosqueName: 'Hacettepe Hastanesi — tarihi eser restorasyonu',
    cityLabel: 'Hacettepe (Ankara)',
    category: 'diger',
    period: '29 Aralık 2018',
    imageSrc: '/hizmetler/ankara-hacettepe-tarihi-eser-restorasyon-2018.webp',
  },
  {
    id: 'istanbul-arnavutkoy-yavuz-sultan-selim-camii-2019',
    plaka: '34',
    mosqueName: 'Yavuz Sultan Selim Camii',
    cityLabel: 'Arnavutköy (İstanbul)',
    category: 'kubbe',
    period: '11 Ocak 2019',
    imageSrc: '/hizmetler/istanbul-arnavutkoy-yavuz-sultan-selim-camii-2019.webp',
  },
  {
    id: 'adana-merkez-isverenler-mehmet-bey-camii-2019',
    plaka: '01',
    mosqueName: 'İşverenler Mehmet Bey Camii',
    cityLabel: 'Merkez (Adana)',
    category: 'kubbe',
    period: '22 Ocak 2019',
    imageSrc: '/hizmetler/adana-merkez-isverenler-mehmet-bey-camii-2019.webp',
  },
  {
    id: 'osmaniye-kadirli-kumbet-koyu-camii-2019',
    plaka: '80',
    mosqueName: 'Kümbet Köyü Camii',
    cityLabel: 'Kümbet Köyü, Kadirli (Osmaniye)',
    category: 'kubbe',
    period: '28 Ocak 2019',
    imageSrc: '/hizmetler/osmaniye-kadirli-kumbet-koyu-camii-2019.webp',
  },
  {
    id: 'adana-yunusoglu-merkez-camii',
    plaka: '01',
    mosqueName: 'Yunusoğlu Merkez Camii',
    cityLabel: 'Yunusoğlu, Merkez (Adana)',
    category: 'kubbe',
    imageSrc: '/hizmetler/adana-yunusoglu-merkez-camii.webp',
  },
  {
    id: 'ankara-kecioren-sentepe-muradiye-camii-2019',
    plaka: '06',
    mosqueName: 'Muradiye Camii',
    cityLabel: 'Şentepe, Keçiören (Ankara)',
    category: 'kubbe',
    period: '27 Nisan 2019',
    imageSrc: '/hizmetler/ankara-kecioren-sentepe-muradiye-camii-2019.webp',
  },
  {
    id: 'ankara-guneykent-memluk-camii-2019',
    plaka: '06',
    mosqueName: 'Memlük Camii',
    cityLabel: 'Güneykent (Ankara)',
    category: 'kubbe',
    period: '21 Mayıs 2019',
    imageSrc: '/hizmetler/ankara-guneykent-memluk-camii-2019.webp',
  },
  {
    id: 'sakarya-sapanca-kirpinar-koyu-camii-2019',
    plaka: '54',
    mosqueName: 'Kırpınar Köyü Camii',
    cityLabel: 'Kırpınar Köyü, Sapanca (Sakarya)',
    category: 'kubbe',
    period: '28 Mayıs 2019',
    imageSrc: '/hizmetler/sakarya-sapanca-kirpinar-koyu-camii-2019.webp',
  },
  {
    id: 'gaziantep-kursun-levha-sevkiyati-2019',
    plaka: '27',
    mosqueName: 'Kurşun levha sevkiyatı',
    cityLabel: 'Gaziantep',
    category: 'diger',
    period: '9 Haziran 2019',
    imageSrc: '/hizmetler/gaziantep-kursun-levha-sevkiyati-2019.webp',
  },
  {
    id: 'bursa-inegol-emir-sultan-camii-2019',
    plaka: '16',
    mosqueName: 'Emir Sultan Camii',
    cityLabel: 'İnegöl (Bursa)',
    category: 'kubbe',
    period: '26 Haziran 2019',
    imageSrc: '/hizmetler/bursa-inegol-emir-sultan-camii-2019.webp',
  },
  {
    id: 'istanbul-camii-alemi-sevkiyati-2019',
    plaka: '34',
    mosqueName: 'Camii alemi sevkiyatı',
    cityLabel: 'İstanbul',
    category: 'diger',
    period: '8 Ağustos 2019',
    imageSrc: '/hizmetler/istanbul-camii-alemi-sevkiyati-2019.webp',
  },
  {
    id: 'malatya-battal-gazi-camii-2020',
    plaka: '44',
    mosqueName: 'Battal Gazi Camii',
    cityLabel: 'Malatya',
    category: 'kubbe',
    period: '1 Temmuz 2020',
    imageSrc: '/hizmetler/malatya-battal-gazi-camii-2020.webp',
  },
  {
    id: 'adiyaman-celikhan-15-temmuz-sehitler-camii-2020',
    plaka: '02',
    mosqueName: '15 Temmuz Şehitler Camii',
    cityLabel: 'Çelikhan (Adıyaman)',
    category: 'kubbe',
    period: '12 Ağustos 2020',
    imageSrc: '/hizmetler/adiyaman-celikhan-15-temmuz-sehitler-camii-2020.webp',
  },
  {
    id: 'amasya-ibecik-koyu-camii-2020',
    plaka: '05',
    mosqueName: 'İbecik Köyü Camii',
    cityLabel: 'İbecik Köyü (Amasya)',
    category: 'kubbe',
    period: '3 Ekim 2020',
    imageSrc: '/hizmetler/amasya-ibecik-koyu-camii-2020.webp',
  },
  {
    id: 'malatya-merkez-camii-2021',
    plaka: '44',
    mosqueName: 'Malatya Merkez Camii',
    cityLabel: 'Malatya',
    category: 'kubbe',
    period: '8 Şubat 2021',
    imageSrc: '/hizmetler/malatya-merkez-camii-2021.webp',
  },
  {
    id: 'konya-aluminyum-levha-sevkiyati-2021',
    plaka: '42',
    mosqueName: 'Alüminyum levha sevkiyatı',
    cityLabel: 'Konya',
    category: 'diger',
    period: '7 Mart 2021',
    imageSrc: '/hizmetler/konya-aluminyum-levha-sevkiyati-2021.webp',
  },
  {
    id: 'mersin-hz-hasan-huseyin-camii-2021',
    plaka: '33',
    mosqueName: 'Hz. Hasan Hüseyin Camii',
    cityLabel: 'Merkez (Mersin)',
    category: 'kubbe',
    period: '16 Mart 2021',
    imageSrc: '/hizmetler/mersin-hz-hasan-huseyin-camii-2021.webp',
  },
  {
    id: 'zonguldak-merkez-cesme-camii-2021',
    plaka: '67',
    mosqueName: 'Merkez Çeşme Camii',
    cityLabel: 'Merkez (Zonguldak)',
    category: 'kubbe',
    period: '28 Haziran 2021',
    imageSrc: '/hizmetler/zonguldak-merkez-cesme-camii-2021.webp',
  },
  {
    id: 'hatay-dortyol-camii-2022',
    plaka: '31',
    mosqueName: 'Dörtyol Camii',
    cityLabel: 'Dörtyol (Hatay)',
    category: 'kubbe',
    period: '20 Şubat 2022',
    imageSrc: '/hizmetler/hatay-dortyol-camii-2022.webp',
  },
  {
    id: 'giresun-universitesi-camii-2022',
    plaka: '28',
    mosqueName: 'Giresun Üniversitesi Camii',
    cityLabel: 'Giresun',
    category: 'kubbe',
    period: '25 Nisan 2022',
    imageSrc: '/hizmetler/giresun-universitesi-camii-2022.webp',
  },
  {
    id: 'tokat-senyuva-camii-2022',
    plaka: '60',
    mosqueName: 'Şenyuva Camii',
    cityLabel: 'Şenyuva (Tokat)',
    category: 'kubbe',
    period: '20 Mayıs 2022',
    imageSrc: '/hizmetler/tokat-senyuva-camii-2022.webp',
  },
  {
    id: 'bartin-aluminyum-satis-sevkiyati-2022',
    plaka: '74',
    mosqueName: 'Alüminyum satışı sevkiyatı',
    cityLabel: 'Bartın',
    category: 'diger',
    period: '15 Ekim 2022',
    imageSrc: '/hizmetler/bartin-aluminyum-satis-sevkiyati-2022.webp',
  },
  {
    id: 'bursa-inegol-erenler-camii-2024',
    plaka: '16',
    mosqueName: 'Erenler Camii',
    cityLabel: 'İnegöl (Bursa)',
    category: 'kubbe',
    period: '29 Mayıs 2024',
    imageSrc: '/hizmetler/bursa-inegol-erenler-camii-2024.webp',
  },
  {
    id: 'mersin-muftulugu-kompleksi-2025',
    plaka: '33',
    mosqueName: 'Mersin Müftülüğü Kompleksi',
    cityLabel: 'Mersin',
    category: 'kubbe',
    period: '28 Aralık 2025',
    imageSrc: '/hizmetler/mersin-muftulugu-kompleksi-2025.webp',
  },
  {
    id: 'balikesir-manyas-merkez-efendi-camii-2026',
    plaka: '10',
    mosqueName: 'Merkez Efendi Camii',
    cityLabel: 'Manyas (Balıkesir)',
    category: 'kubbe',
    period: '3 Mart 2026',
    imageSrc: '/hizmetler/balikesir-manyas-merkez-efendi-camii-2026.webp',
  },
];

export type ReferenceFilter = 'all' | ReferenceCategory;

export function filterReferenceProjects(
  list: readonly TurkeyReferenceProject[],
  filter: ReferenceFilter
): TurkeyReferenceProject[] {
  if (filter === 'all') return [...list];
  if (filter === 'diger') return list.filter((p) => p.category === 'diger');
  return list.filter((p) => p.category === filter);
}

export function countUniqueProvinces(list: readonly TurkeyReferenceProject[]): number {
  return new Set(list.map((p) => p.plaka.padStart(2, '0'))).size;
}

export function categoryLabelTr(c: ReferenceCategory): string {
  switch (c) {
    case 'kubbe':
      return 'Kubbe kaplama';
    case 'nakkas':
      return 'Nakkaş süsleme';
    case 'oluk':
      return 'Oluk satışı ve montajı';
    default:
      return 'Diğer / sevkiyat';
  }
}
